version: '3.4'

x-common-variables: &common-variables
 CELERY_BROKER_URL: redis://redis:6379
 CELERY_RESULT_BACKEND: redis://redis:6379
 MINIO_ACCESS_KEY: minio
 MINIO_SECRET_KEY: minio123
 MINIO_URL: minio:9000
 MINIO_BUCKET_NAME: hse-api-bucket
 RESTRICTED_MODE: 0

services:
 hse-api-web:
  build: .
  ports:
   - "80:80"
  links:
   - redis
   - minio
   - hse-api-celery
  environment: *common-variables

 hse-api-celery:
  build: .
  command: celery -A main.celery worker
  links:
   - redis
   - minio
  environment: *common-variables

 minio:
  image: minio/minio:latest
  volumes:
   - data:/data
  ports:
   - "9000:9000"
  command: server /data/minio
  environment: *common-variables

 redis:
  image: redis:latest

volumes:
  data:
